name = "baxopf_enhancement"
modname = "baxopf_enhancement"
prefix = "BAxOPF"
author = "Rampage"
mainprefix = "z"
sig_version = 3

files = [
	"mod.cpp",
	"meta.cpp",
	"*.paa"
]
include = [
    "./include"
]

key_name = "{{prefix}}-{{version}}"
authority = "{{prefix}}-{{version}}-{{git \"id 8\"}}"

releasebuild = []

show_output = true

[header_exts]
version= "{{git \"id 8\"}}"